//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public Iletisim()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int IletisimId { get; set; }
        public string CepTel { get; set; }
        public string EPosta { get; set; }
        public string EvAdresi { get; set; }
        public string EvAdresiIl { get; set; }
        public string EvAdresiIlce { get; set; }
        public string EvTel { get; set; }
        public string EvPostaKodu { get; set; }
        public string IsAdresi { get; set; }
        public string IsAdresiIl { get; set; }
        public string IsAdresiIlce { get; set; }
        public string IsTel { get; set; }
        public string IsFax { get; set; }
        public string IsVergiDairesiNo { get; set; }
        public string IsPostaKodu { get; set; }
        public string YakiniAd { get; set; }
        public string YakiniSoyad { get; set; }
        public string YakinlikDerecesi { get; set; }
        public string YakiniAdresi { get; set; }
        public string YakiniAdresiIl { get; set; }
        public string YakiniAdresiIlce { get; set; }
        public string YakiniCepTel { get; set; }
        public string YakiniPostaKodu { get; set; }
        public string YakiniEPosta { get; set; }
    
        public virtual ICollection<Personel> Personel { get; set; }
    }
}
