//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsgEntities : DbContext
    {
        public IsgEntities()
            : base("name=IsgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Iletisim> Iletisim { get; set; }
        public DbSet<Kimlik> Kimlik { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Muayene> Muayene { get; set; }
        public DbSet<Ogrenim> Ogrenim { get; set; }
        public DbSet<Personel> Personel { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Sabika> Sabika { get; set; }
        public DbSet<Saglik> Saglik { get; set; }
    }
}
