//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kimlik
    {
        public Kimlik()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int KimlikId { get; set; }
        public Nullable<int> ResimId { get; set; }
        public string TcNo { get; set; }
        public string Seri { get; set; }
        public Nullable<int> No { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int Cinsiyet { get; set; }
        public string BabaAdi { get; set; }
        public string AnaAdi { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public int MedeniHal { get; set; }
        public string Din { get; set; }
        public int KanGrubu { get; set; }
        public string MahalleKoy { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string CiltNo { get; set; }
        public string AileSiraNo { get; set; }
        public string SiraNo { get; set; }
        public string VerildigiYer { get; set; }
        public string VerilisNedeni { get; set; }
        public Nullable<int> KayitNo { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
    
        public virtual ICollection<Personel> Personel { get; set; }
    }
}
