//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int KullaniciId { get; set; }
        public string TcNo { get; set; }
        public string Isim { get; set; }
        public string SoyIsim { get; set; }
        public string Eposta { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> RolId { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
