//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muayene
    {
        public int MuayeneId { get; set; }
        public Nullable<System.DateTime> MuayeneTarih { get; set; }
        public string Departman { get; set; }
        public Nullable<int> Meslek { get; set; }
        public Nullable<int> MuayeneTur { get; set; }
        public Nullable<int> MuayeneSonuc { get; set; }
        public Nullable<int> Bildirim { get; set; }
        public Nullable<bool> Istirahat { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<bool> Sevk { get; set; }
        public Nullable<int> DoktorId { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
