//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS_Otomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenim
    {
        public Ogrenim()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int OgrenimId { get; set; }
        public Nullable<int> ResimId { get; set; }
        public string VerenKurum { get; set; }
        public string BelgeTuru { get; set; }
        public Nullable<System.DateTime> BelgeTarihi { get; set; }
        public string BelgeSayisi { get; set; }
    
        public virtual ICollection<Personel> Personel { get; set; }
    }
}
